### ISSUE TITLE
...

### ISSUE THREAD

**Issue by nobitakizi** [duyet-website/api.duyet.net#1]
## Hai ý tưởng lớn gặp nhau nhưng bất đồng ngôn ngữ

Mình là Nobita Kizi, chuyên viên lập trình điện toán PHP. Nghe thấy API, vội vàng vô xem có gì để học tập nhưng xem ra chưa phát triển lắm

Những cái rất cần mà bạn còn thiếu : whois, scan dns, check ip proxy, check email spam, weather, code beautiful , get facebook graph,google transfer,...

Còn nhiều lắm. API mình xây dựng mới có 30 chức năng còn chưa dám đưa ra public này

**Comment by duyetdev** [comment]
Chào bạn, rất vui khi nhận được sự quan tâm từ bạn. 
Những apis bạn liệt kệ thực sự mình không cần, vì mình làm (và hướng đến các đối tượng) trong lĩnh vực Machine Learning và Data Science. 
Phần mềm nào cũng cần có thì gian phát triển dần từ từ nhờ phản hồi từ cộng đồng. 

Dù sao mình cũng luôn rất hoan nghênh mọi đóng góp từ mọi người. Chúc vui :)
